networks:
  ds-net:
    driver: bridge

volumes:
  pgdata:

services:
  traefik:
    container_name: traefik
    image: traefik:2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ds-net

  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enrollment
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - ds-net
    ports:
      - "5432:5432"

  gateway:
    container_name: gateway
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    depends_on:
      - db
      - auth-service
      - course-service
      - enrollment-service
      - grade-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/enrollment
      AUTH_HTTP_TARGET: http://auth-service:8001
      AUTH_GRPC_TARGET: auth-service:50051
      COURSE_GRPC_TARGET: course-service:50052
      ENROLLMENT_GRPC_TARGET: enrollment-service:50053
      GRADE_GRPC_TARGET: grade-service:50054
      CORS_ALLOW_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      CURRENT_TERM: "2"          
      CURRENT_ACADEMIC_YEAR: "2025-2026"

    labels:
      - traefik.enable=true
      - traefik.http.routers.gateway.rule=PathPrefix(`/api`)
      - traefik.http.routers.gateway.entrypoints=web
      - traefik.http.routers.gateway.priority=10
      - traefik.http.routers.gateway.service=gateway
      - traefik.http.services.gateway.loadbalancer.server.port=8000
      - traefik.http.services.gateway.loadbalancer.healthcheck.path=/health
      - traefik.http.services.gateway.loadbalancer.healthcheck.interval=10s
      - traefik.http.routers.gateway-health.rule=PathPrefix(`/health/gateway`)
      - traefik.http.routers.gateway-health.entrypoints=web
      - traefik.http.routers.gateway-health.service=gateway
      - traefik.http.routers.gateway-health.middlewares=gateway-health-rewrite
      - traefik.http.middlewares.gateway-health-rewrite.replacepath.path=/health
    networks:
      - ds-net
    ports:
      - "8000:8000"

  auth-service:
    build:
      context: ..                  # repo root as build context
      dockerfile: auth-service/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/enrollment
    networks:
      - ds-net
    ports:
      - "8001:8001"
      - "50051:50051"
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth-health.rule=PathPrefix(`/health/auth`)
      - traefik.http.routers.auth-health.entrypoints=web
      - traefik.http.routers.auth-health.service=auth-service
      - traefik.http.routers.auth-health.middlewares=auth-health-rewrite
      - traefik.http.middlewares.auth-health-rewrite.replacepath.path=/health
      - traefik.http.services.auth-service.loadbalancer.server.port=8001
      - traefik.http.services.auth-service.loadbalancer.healthcheck.path=/health
      - traefik.http.services.auth-service.loadbalancer.healthcheck.interval=10s

  course-service:
    build:
      context: ..
      dockerfile: course-service/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/enrollment
    networks:
      - ds-net
    expose:
      - "8002"
      - "50052"
    labels:
      - traefik.enable=true
      - traefik.http.routers.course.rule=PathPrefix(`/svc/course`)
      - traefik.http.routers.course.entrypoints=web
      - traefik.http.routers.course.service=course-service
      - traefik.http.routers.course.middlewares=course-strip
      - traefik.http.middlewares.course-strip.stripprefix.prefixes=/svc/course
      - traefik.http.routers.course-health.rule=PathPrefix(`/health/course`)
      - traefik.http.routers.course-health.entrypoints=web
      - traefik.http.routers.course-health.service=course-service
      - traefik.http.routers.course-health.middlewares=course-health-rewrite
      - traefik.http.middlewares.course-health-rewrite.replacepath.path=/health
      - traefik.http.services.course-service.loadbalancer.server.port=8002
      - traefik.http.services.course-service.loadbalancer.healthcheck.path=/health
      - traefik.http.services.course-service.loadbalancer.healthcheck.interval=10s

  enrollment-service:
    build:
      context: ..
      dockerfile: enrollment-service/Dockerfile
    depends_on:
      - db
      - auth-service
      - course-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/enrollment
    networks:
      - ds-net
    ports:
      - "8003:8003"
      - "50053:50053"
    labels:
      - traefik.enable=true
      - traefik.http.routers.enrollment-health.rule=PathPrefix(`/health/enrollment`)
      - traefik.http.routers.enrollment-health.entrypoints=web
      - traefik.http.routers.enrollment-health.service=enrollment-service
      - traefik.http.routers.enrollment-health.middlewares=enrollment-health-rewrite
      - traefik.http.middlewares.enrollment-health-rewrite.replacepath.path=/health
      - traefik.http.services.enrollment-service.loadbalancer.server.port=8003
      - traefik.http.services.enrollment-service.loadbalancer.healthcheck.path=/health
      - traefik.http.services.enrollment-service.loadbalancer.healthcheck.interval=10s

  grade-service:
    build:
      context: ..
      dockerfile: grade-service/Dockerfile
    depends_on:
      - db
      - auth-service
      - course-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/enrollment
    networks:
      - ds-net
    ports:
      - "8004:8004"
      - "50054:50054"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grade-health.rule=PathPrefix(`/health/grade`)
      - traefik.http.routers.grade-health.entrypoints=web
      - traefik.http.routers.grade-health.service=grade-service
      - traefik.http.routers.grade-health.middlewares=grade-health-rewrite
      - traefik.http.middlewares.grade-health-rewrite.replacepath.path=/health
      - traefik.http.services.grade-service.loadbalancer.server.port=8004
      - traefik.http.services.grade-service.loadbalancer.healthcheck.path=/health
      - traefik.http.services.grade-service.loadbalancer.healthcheck.interval=10s

  frontend:
    container_name: frontend
    build: ../frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
      VITE_API_BASE: http://localhost:8000/api
    ports:
      - "3000:3000"
    networks:
      - ds-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.priority=1
      - traefik.http.services.frontend.loadbalancer.server.port=3000
